/**
 * Client-side decoding of opaque pagination cursors. Cursors are generated by
 * the server (base64url of a small JSON pair) and carried unchanged by the
 * client; they are decoded here only to compare anchors when merging
 * pagination across per-schema queries ({@link useAllEntries}).
 */

/** Decoded cursor anchor: the row's sort-column value plus its content.id. */
export interface DecodedCursor {
  /** Sort-column value of the anchor row; null = SQL NULL sort value. */
  value: number | string | null;
  id: number;
}

/**
 * Decode an opaque cursor. Returns null for missing or undecodable input
 * (treated as "no cursor"). A bare positive integer is accepted as a legacy
 * id cursor (`value` and `id` both the integer).
 */
export function decodeCursor(raw: string | null | undefined): DecodedCursor | null {
  if (raw === undefined || raw === null) return null;
  const s = String(raw).trim();
  if (s === "") return null;

  // Legacy bare-id cursor from pre-keyset clients.
  if (/^\d+$/.test(s)) {
    const n = Number(s);
    if (!Number.isSafeInteger(n) || n < 1) return null;
    return { value: n, id: n };
  }

  // Opaque cursor: base64url of JSON { v, i }.
  try {
    const b64 = s.replace(/-/g, "+").replace(/_/g, "/");
    const padded = b64 + "=".repeat((4 - (b64.length % 4)) % 4);
    const binary = atob(padded);
    const bytes = Uint8Array.from(binary, (c) => c.charCodeAt(0));
    const json = new TextDecoder().decode(bytes);
    const obj: unknown = JSON.parse(json);
    if (typeof obj !== "object" || obj === null || Array.isArray(obj)) return null;
    const { v, i } = obj as { v?: unknown; i?: unknown };
    if (v !== null && typeof v !== "string" && typeof v !== "number") return null;
    if (typeof i !== "number" || !Number.isSafeInteger(i) || i < 1) return null;
    return { value: v, id: i };
  } catch {
    return null;
  }
}

/**
 * Natural ascending comparison of two decoded cursor anchors: sort value
 * ascending (numbers before strings, NULLs last), then content.id ascending.
 * For id-based cursors this reduces to comparing the ids themselves.
 */
export function compareCursors(a: DecodedCursor, b: DecodedCursor): number {
  const av = a.value;
  const bv = b.value;
  if (av === null && bv === null) return a.id - b.id;
  if (av === null) return 1;
  if (bv === null) return -1;
  if (typeof av === "number" && typeof bv === "number") {
    if (av !== bv) return av < bv ? -1 : 1;
  } else if (typeof av === "string" && typeof bv === "string") {
    if (av !== bv) return av < bv ? -1 : 1;
  } else if (typeof av !== typeof bv) {
    return typeof av === "number" ? -1 : 1;
  }
  return a.id - b.id;
}

/**
 * Compare two opaque cursor strings by their decoded anchors. Returns null
 * when either side is undecodable (server-generated cursors always decode).
 */
export function compareRawCursors(a: string, b: string): number | null {
  const da = decodeCursor(a);
  const db = decodeCursor(b);
  if (da === null || db === null) return null;
  return compareCursors(da, db);
}
